sudo: required
services:
  - docker

before_install:
  - docker build -t aberdovic/docker-react -f Dockerfile.dev .

script:
  - docker run aberdovic/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-aleksandar"
  env: "DockerAleksandar-env"
  bucket_name: "elasticbeanstalk-us-east-2-154945846589"
  bucket_path: "docker-aleksandar"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key:
  secure: "$AWS_SECRET_KEY"